# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title MetropolisC
#' @description The Rcpp function in homework.
#' @param sigma the variance of the normal
#' @param x0 the initial value
#' @param N the number of the trying
#' @return the path and the number of the accept point
#' @useDynLib SC19025
#' @examples
#' \dontrun{
#' x<-Metropolisc(1,25,2000)
#' x
#' }
#' @export
MetropolisC <- function(sigma, x0, N) {
    .Call('_SC19025_MetropolisC', PACKAGE = 'SC19025', sigma, x0, N)
}

